version: 2
jobs:
  install_yarn:
    docker:
      - image: node:latest
    steps:
      - restore_cache:
          key: yarn-bin
      - run:
          name: Install yarn
          command: npm i yarn -g
      - save_cache:
          paths:
            - /usr/local/lib/node_modules
            - /usr/local/bin/yarn
          key: yarn-bin-{{ checksum "/usr/local/lib/node_modules/yarn/package.json"}}
      - persist_to_workspace:
          root: /usr/local/lib
          paths:
            - node_modules
      - persist_to_workspace:
          root: /usr/local/bin
          paths:
            - yarn
  install_app:
    docker:
      - image: node:latest
    steps:
      - attach_workspace:
          at: /usr/local/lib
      - attach_workspace:
          at: /usr/local/bin
      - restore_cache:
          key: yarn-cache
      - checkout:
          path: ~/project
      - run:
          name: Install app
          command: yarn
      - save_cache:
          paths:
            - ~/.cache/yarn
          key: yarn-cache-{{ checksum "yarn.lock" }}
      - persist_to_workspace:
          root: ~/
          paths:
            - project
  test_6:
    docker:
      - image: node:6
    steps:
      - attach_workspace:
          at: /usr/local/lib
      - attach_workspace:
          at: /usr/local/bin
      - attach_workspace:
          at: ~/
      - run:
          name: Run tests
          command: yarn test
  test_8:
    docker:
      - image: node:8
    steps:
      - attach_workspace:
          at: /usr/local/lib
      - attach_workspace:
          at: /usr/local/bin
      - attach_workspace:
          at: ~/
      - run:
          name: Run tests
          command: yarn test
      - persist_to_workspace:
          root: ~/project
          paths:
            - coverage
  coverage:
    docker:
      - image: node:latest
    steps:
      - attach_workspace:
          at: ~/
      - attach_workspace:
          at: ~/project
      - run:
          name: Code coverage
          command: |
            npx codecov
            cat coverage/lcov.info | npx codacy-coverage
  greenkeeper_lockfile_update:
    docker:
      - image: node:latest
    steps:
      - attach_workspace:
          at: /usr/local/lib
      - attach_workspace:
          at: /usr/local/bin
      - attach_workspace:
          at: ~/
      - run :
          name: Greenkeeper lockfile update
          command: npx --package greenkeeper-lockfile greenkeeper-lockfile-update
      - persist_to_workspace:
          root: ~/
          paths:
            - project
  greenkeeper_lockfile_upload:
    docker:
      - image: node:latest
    steps:
      - attach_workspace:
          at: /usr/local/lib
      - attach_workspace:
          at: /usr/local/bin
      - attach_workspace:
          at: ~/
      - run :
          name: Greenkeeper lockfile upload
          command: npx --package greenkeeper-lockfile greenkeeper-lockfile-upload

workflows:
  version: 2
  test:
    jobs:
      - install_yarn
      - install_app:
          requires:
            - install_yarn
      - greenkeeper_lockfile_update:
          requires:
            - install_app
      - test_6:
          requires:
            - greenkeeper_lockfile_update
      - test_8:
          requires:
            - greenkeeper_lockfile_update
      - coverage:
          requires:
            - test_8
            - test_6
      - greenkeeper_lockfile_upload:
          requires:
            - test_8
            - test_6
