version: 2
jobs:
  install_yarn:
    docker:
      - image: node:latest
    steps:
      - restore_cache:
          key: yarn-bin
      - run:
          name: Install yarn
          command: npm i yarn -g
      - save_cache:
          paths:
            - /usr/local/lib/node_modules
            - /usr/local/bin/yarn
          key: yarn-bin-{{ checksum "/usr/local/lib/node_modules/yarn/package.json"}}
      - persist_to_workspace:
          root: /usr/local/lib
          paths:
            - node_modules
      - persist_to_workspace:
          root: /usr/local/bin
          paths:
            - yarn
  install_app:
    docker:
      - image: node:latest
    steps:
      - attach_workspace:
          at: /usr/local/lib
      - attach_workspace:
          at: /usr/local/bin
      - restore_cache:
          key: yarn-cache
      - checkout:
          path: ~/project
      - run:
          name: Install app
          command: yarn
      - save_cache:
          paths:
            - ~/.cache/yarn
          key: yarn-cache-{{ checksum "yarn.lock" }}
      - persist_to_workspace:
          root: ~/
          paths:
            - project
  test_6:
    docker:
      - image: node:6
    steps:
      - attach_workspace:
          at: /usr/local/lib
      - attach_workspace:
          at: /usr/local/bin
      - attach_workspace:
          at: ~/
      - run:
          name: Run tests
          command: yarn test
  test_8:
    docker:
      - image: node:8
    steps:
      - attach_workspace:
          at: /usr/local/lib
      - attach_workspace:
          at: /usr/local/bin
      - attach_workspace:
          at: ~/
      - run:
          name: Run tests
          command: yarn test
      - run:
          name: Code coverage
          command: npx codecov

workflows:
  version: 2
  test:
    jobs:
      - install_yarn
      - install_app:
          requires:
            - install_yarn
      - test_6:
          requires:
            - install_app
      - test_8:
          requires:
            - install_app
          
